apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/jacekszlachtass/argo-test-app/base?ref=v0.0.1

commonLabels:
  env: dev

images:
- name: fow-backend-for-frontend
  newName: europe-west2-docker.pkg.dev/fow-dev-1234/docker/fow-test-image
  newTag: db03bf0575a45c005ca276e714ee6a273fd9f233
- name: fow-be
  newName: europe-west2-docker.pkg.dev/fow-dev-1234/docker/fow-test-image
  newTag: db03bf0575a45c005ca276e714ee6a273fd9f233
