apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/jacekszlachtass/argo-test-app/base?ref=v0.0.4

commonLabels:
  env: dev

images:
- name: fow-backend-for-frontend
  newName: europe-west2-docker.pkg.dev/fow-dev-1234/docker/fow-test-image
  newTag: 0bce69847ffde26481a9a1b420bff3820b5b9c32
- name: fow-be
  newName: europe-west2-docker.pkg.dev/fow-dev-1234/docker/fow-test-image
  newTag: 0bce69847ffde26481a9a1b420bff3820b5b9c32
