apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jacek-argo-test-dev
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.github-trigger-workflow: ""
    notifications.argoproj.io/subscribe.on-deployed.gmail: "jacek.szlachta@sullivanstanleyassociates.com"
spec:
  project: default

  source:
    repoURL: https://github.com/jacekszlachtass/argo-test-app.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: jacek-argo-test-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

