apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jacek-argo-test-stage
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jacekszlachtass/argo-test-app.git
    targetRevision: HEAD
    path: overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: jacek-argo-test-stage

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

