name: test_workflow
on:
  workflow_dispatch:
    inputs:
      target_revision:
        description: 'target revision'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        echo "Target Revision: ${{ github.event.inputs.target_revision }}"
      
